 const people = [
    { name: "Alice Johnson", id: crypto.randomUUID(), age: 28, country: "USA", profession: "Engineer" },
    { name: "Liam O'Connor", id: crypto.randomUUID(), age: 32, country: "Ireland", profession: "Artist" },
    { name: "Sofia Rossi", id: crypto.randomUUID(), age: 25, country: "Italy", profession: "Designer" },
    { name: "Yuki Takahashi", id: crypto.randomUUID(), age: 30, country: "Japan", profession: "Developer" },
    { name: "Elena Ivanova", id: crypto.randomUUID(), age: 29, country: "Russia", profession: "Doctor" },
    { name: "Mateo Garcia", id: crypto.randomUUID(), age: 35, country: "Spain", profession: "Chef" },
    { name: "Amara Ndlovu", id: crypto.randomUUID(), age: 27, country: "South Africa", profession: "Teacher" },
    { name: "Jasper van der Meer", id: crypto.randomUUID(), age: 31, country: "Netherlands", profession: "Architect" },
    { name: "Chloe Dupont", id: crypto.randomUUID(), age: 26, country: "France", profession: "Journalist" },
    { name: "Omar Hassan", id: crypto.randomUUID(), age: 34, country: "Egypt", profession: "Lawyer" },
    { name: "Aisha Khan", id: crypto.randomUUID(), age: 29, country: "Pakistan", profession: "Scientist" },
    { name: "Nina Müller", id: crypto.randomUUID(), age: 30, country: "Germany", profession: "Nurse" },
    { name: "Thiago Silva", id: crypto.randomUUID(), age: 33, country: "Brazil", profession: "Musician" },
    { name: "Zara Ahmed", id: crypto.randomUUID(), age: 28, country: "UK", profession: "Social Worker" },
    { name: "Kira Petrov", id: crypto.randomUUID(), age: 27, country: "Bulgaria", profession: "Photographer" },
    { name: "Luca Moretti", id: crypto.randomUUID(), age: 31, country: "Italy", profession: "Web Developer" },
    { name: "Maya Kim", id: crypto.randomUUID(), age: 26, country: "South Korea", profession: "Researcher" },
    { name: "Santiago Pérez", id: crypto.randomUUID(), age: 29, country: "Chile", profession: "Marketing Specialist" },
    { name: "Ingrid Svensson", id: crypto.randomUUID(), age: 34, country: "Sweden", profession: "Data Analyst" },
    { name: "Ravi Patel", id: crypto.randomUUID(), age: 32, country: "India", profession: "Project Manager" },
    { name: "Cecilia Alvarado", id: crypto.randomUUID(), age: 28, country: "Mexico", profession: "Graphic Designer" },
    { name: "James Smith", id: crypto.randomUUID(), age: 40, country: "USA", profession: "Pilot" },
    { name: "Isabella Martinez", id: crypto.randomUUID(), age: 23, country: "Spain", profession: "Content Writer" },
    { name: "Liam Wang", id: crypto.randomUUID(), age: 37, country: "China", profession: "Software Engineer" },
    { name: "Khadija Al-Mansoori", id: crypto.randomUUID(), age: 29, country: "UAE", profession: "Financial Analyst" },
    { name: "Oliver Brown", id: crypto.randomUUID(), age: 31, country: "Australia", profession: "Veterinarian" },
    { name: "Mia Thompson", id: crypto.randomUUID(), age: 26, country: "Canada", profession: "Pharmacist" },
    { name: "Taro Saito", id: crypto.randomUUID(), age: 35, country: "Japan", profession: "IT Consultant" },
    { name: "Fatima Al-Sayed", id: crypto.randomUUID(), age: 27, country: "Saudi Arabia", profession: "Teacher" },
    { name: "Emma Wilson", id: crypto.randomUUID(), age: 22, country: "New Zealand", profession: "Research Scientist" },
    { name: "Victor Hugo", id: crypto.randomUUID(), age: 38, country: "France", profession: "Chef" },
    { name: "Natalia Costa", id: crypto.randomUUID(), age: 33, country: "Brazil", profession: "Fashion Designer" },
    { name: "Noah Kim", id: crypto.randomUUID(), age: 30, country: "South Korea", profession: "Engineer" },
    { name: "Layla Ahmed", id: crypto.randomUUID(), age: 24, country: "Egypt", profession: "Nurse" },
    { name: "Finn O'Sullivan", id: crypto.randomUUID(), age: 29, country: "Ireland", profession: "Web Developer" },
    { name: "Lina Zhang", id: crypto.randomUUID(), age: 28, country: "China", profession: "Teacher" },
    { name: "Jack Taylor", id: crypto.randomUUID(), age: 32, country: "UK", profession: "Lawyer" },
    { name: "Sophie Dupuis", id: crypto.randomUUID(), age: 26, country: "France", profession: "Journalist" },
    { name: "Ethan Lee", id: crypto.randomUUID(), age: 36, country: "USA", profession: "Photographer" },
    { name: "Gabriel Almeida", id: crypto.randomUUID(), age: 27, country: "Portugal", profession: "Data Scientist" },
    { name: "Ava Garcia", id: crypto.randomUUID(), age: 25, country: "Mexico", profession: "Marketing Manager" },
    { name: "Samir Nasr", id: crypto.randomUUID(), age: 31, country: "Morocco", profession: "Architect" },
    { name: "Rina Patel", id: crypto.randomUUID(), age: 29, country: "India", profession: "Software Developer" },
    { name: "David Martin", id: crypto.randomUUID(), age: 34, country: "Spain", profession: "Engineer" },
    { name: "Olivia White", id: crypto.randomUUID(), age: 28, country: "USA", profession: "Veterinarian" },
    { name: "Jonas Fischer", id: crypto.randomUUID(), age: 30, country: "Germany", profession: "Data Analyst" },
    { name: "Leila Dakhil", id: crypto.randomUUID(), age: 32, country: "Tunisia", profession: "Content Creator" },
    { name: "Aria Moreau", id: crypto.randomUUID(), age: 24, country: "Canada", profession: "Physiotherapist" },
    { name: "Tommy Harrison", id: crypto.randomUUID(), age: 36, country: "Australia", profession: "Logistics Manager" },
    { name: "Chloe Lee", id: crypto.randomUUID(), age: 27, country: "New Zealand", profession: "Environmental Scientist" },
    { name: "Nicoleta Ionescu", id: crypto.randomUUID(), age: 29, country: "Romania", profession: "Teacher" },
    { name: "Julian Schmidt", id: crypto.randomUUID(), age: 31, country: "Germany", profession: "Research Scientist" },
    { name: "Elif Korkmaz", id: crypto.randomUUID(), age: 33, country: "Turkey", profession: "Software Engineer" },
    { name: "Emilia Rossi", id: crypto.randomUUID(), age: 25, country: "Italy", profession: "Photographer" },
    { name: "Kian Mendez", id: crypto.randomUUID(), age: 34, country: "Mexico", profession: "Teacher" },
  ];
  
  export default people